services:
  restuarent-website:
    build: . # Tells Docker Compose to build the image from the Dockerfile in the current directory
    ports:
      - "8080:80" # Map port 8080 on your host to port 80 in the container
    # If you have many files, you can mount the entire directory:
    volumes:
      - ./:/usr/share/nginx/html