apiVersion: apps/v1
kind: Deployment
metadata:
  name: restuarent-website-deployment
spec:
  replicas: 3 # You can increase this for more instances
  selector:
    matchLabels:
      app: restuarent-website
  template:
    metadata:
      labels:
        app: restuarent-website
    spec:
      containers:
      - name: simple-website-container
        image: bhuvanmdev/restuarent-website:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: restuarent-website-service
spec:
  selector:
    app: restuarent-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort