apiVersion: v1
kind: Service
metadata:
  name: restuarent-website-service
spec:
  selector:
    app: restuarent-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort