apiVersion: apps/v1
kind: Deployment
metadata:
  name: restuarent-website-deployment
spec:
  replicas: 3 # You can increase this for more instances
  selector:
    matchLabels:
      app: restuarent-website
  template:
    metadata:
      labels:
        app: restuarent-website
    spec:
      containers:
      - name: simple-website-container
        image: bhuvanmdev/restuarent-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
